config/routes.rb
Rails.application.routes.draw do
  resources :products
  #root 'products#index'
  root 'top#main'
  get 'top/main'
  resources :cart_items, only: [:new, :create, :destroy]
  resources :carts, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cartitems
    #has_many :cartitem_products, through: :cartitems, source: :products
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
    #belongs_to :product
    #belongs_to :cart
    validates :qty, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
    #has_one :cartitem
    #has_one :cartitem_cart, through: :cartitem, source: :cart
    validates :name, presence: true
    validates :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_cart
    private
    def current_cart
        if session[:cart_id]
            cart = Cart.find(session[:cart_id])
        else
            cart = Cart.create
            session[:cart_id] = cart.id
        end
        cart
    end
end

app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController
  def new
    @cartitem = Cartitem.new
  end
  
  def create
    @cartitem = Cartitem.new(qty: params[:cartitem][:qty], product_id: params[:product][:id], cart_id: current_cart)
    @cartitem.save
    redirect_to products_path
  end
  
  def destroy
    cartitem = Cartitem.find(params[:cartitem][:product_id])
    cartitem.destroy
    redirect_to cart_path(current_cart)
  end
end
  
 

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cartitems = Cartitem.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(name: params[:product][:name], price: params[:product][:price])
    @product.save
    redirect_to products_path
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to products_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    redirect_to products_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cartitems/new.html.erb
<h1>追加画面</h1>
<p>商品名称：<%= Product.find_by(id: params[:cartitem][:product_id]).name %></p>
<p>商品価格：<%= Product.find_by(id: params[:cartitem][:product_id]).price %>円</p>
<%= form_for @cartitem , url: {action: :create} do |f| %>
    <%= f.label :qty, '数量:' %>
    <%= f.text_field :qty %>
    <%= f.submit '商品を登録する' %>
<% end %>

app/views/carts/show.html.erb
<h1>カート一覧</h1>
<hr>
<% @cartitems.each do |e| %>
  <%= Product.find_by(id: params[:cartitem][:product_id]).name %>
  <%= Product.find_by(id: params[:cartitem][:product_id]).price %>
  <%= link_to 'カートから削除', cart_item_path(e), data: { turbo_method: :delete } %>
<% end %>

<p>
  合計料金：<% sum = 0 %>
  <% @cartitems.each do |e| %>
    <% sum += (Product.find_by(id: params[:cartitem][:product_id]).price * params[:cartitem][:qty])%>
  <% end %>
  <%= sum %>円
</p>


<%= link_to '商品一覧に戻る', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>商品一覧</h1>
<hr>
<% @products.each do |pro| %>
  <p>名前：<%= pro.name %></p>
  <p>価格：<%= pro.price %>円</p>
  <p>
    <%= link_to '削除', product_path(pro), data: { turbo_method: :delete } %>
    <%= link_to 'カートに追加', new_cart_item_path(product_id: pro.id) %>
  </p>
  <hr>
<% end %>
<%= link_to '商品を追加する', new_product_path %>
<%= link_to 'カートを見る', cart_path(current_cart) %>

app/views/products/new.html.erb
<h1>商品登録画面</h1>
<%= form_for @product , url: {action: :create} do |f| %>
    <%= f.label :name, '商品名' %>
    <%= f.text_field :name %>
    <%= f.label :price, '商品価格' %>
    <%= f.text_field :price %>
    <%= f.submit '登録' %>
<% end %>

app/views/top/main.html.erb
<h1>Top#main</h1>
<p>Find me in app/views/top/main.html.erb</p>